### PR TITLE
Build Workflow

### PR DESCRIPTION
**Pull request by briandelmsft**
This will add a GitHub action that will build the necessary zip file and upload the ZIP file to a Azure Storage Account in my tenant.

This will allow us to point our own installs at a private version that will automatically update with any new commits.

This workflow will only create builds on the main branch and any branches starting with the word build

### CODE REVIEW

**Comment by piaudonn** [comment]
is there a way for me to test that?

**Comment by briandelmsft** [comment]
@piaudonn yes, create a new branch based on the workflow branch that starts with build (once this PR is merged you will be able to base the branch off main, but until then the workflow only executes if you base it on the workflow branch)

After the branch is created a build will initiate and after about 2 minutes you'll find a zip file called branchname-stat.zip in that statbuild of the briandel storage account in my Azure subscription.  You could then point your function directly to that (using a SAS) to run it.  You will also be able to verify on the actions tab of the repo that the job ran

**Comment by briandelmsft** [comment]
I made a small change to this where the action won't run until you actually change a relevant file.  something in classes modules shared, or requrements.txt / host.json

**Review by piaudonn — APPROVED** [review]
WAD

**Pull request merged**
